baseURL = 'https://www.hugojvb.com/'
staticDir = ['static']

[languages]
  [languages.en]
    title = "Hugo B | Software Engineer"
    weight = 1
  [languages.es]
    title = "Hugo B | Ingeniero de Software"
    weight = 2
  [language.pt]
    title = "Hugo B | Engenheiro de Software"
    weight = 3